ipdb/__main__.py

Now load a full IPythonApp in the background in order to retrieve the
configuration and inject it into ipdb.
If an instance of IPython is already running its configuration will be loaded.
If it is an embed shell and no IPythonApp is running, the logic is usually in a
python script and you will have to change the code in order to make it works.

Load IPython configuration into ipdb

---

ipdb/__main__.py

TerminalIPythonApp.initialize chokes on sys.argv if the process isn't an IPython shell.

Don't pass sys.argv to IPython for configuration

---

ipdb/__main__.py

The removed import was unused anyway.

Fix import failure on older ipython versions

---

ipdb/__main__.py

This parameter is optional in pdb:
https://docs.python.org/3.5/library/pdb.html#pdb.post_mortem
so ipdb should provide the same API.

Don't require users to pass a traceback to post_mortem

---

HISTORY.txt
README.rst
ipdb/__init__.py
ipdb/__main__.py
ipdb/stdout.py
setup.py

Like needed by `nose`.
Rather, provide a set of functions that can be called explicitely when needed.
drop support of IPython before 0.10.2

Stop trying to magically guess when stdout needs to be captured.

---

ipdb/__main__.py

A solution for #105 
It seems like a good place to start getting the ball rolling. Thoughts?

ipython5 use TerminalInteractiveShell debugger_cls solution for #105

---

ipdb/__main__.py

Commands can now be passed on the command line.
e.g.
```ipdb -c "until file.py:23" file.py```
Sets a breakpoint on line 23.
Runs script until breakpoint or exception.
This is consistent with standard library module pdb.

Command line usage consistent with pdb - Add argument commands

---

.travis.yml
ipdb/__main__.py
setup.py

This makes ipdb require IPython >=5. Version 5.0.0 came out in July 2016, about 18 months ago. It's probably possible to support older versions as well, but all the compatibility code makes it much harder to understand the code.
Closes gh-142
Closes gh-99
Closes gh-81

Simplify loading IPython and getting information from it

---

.travis.yml
AUTHORS
COPYING.txt
HISTORY.txt
setup.py

Python 3.3.x reached the "end of life" status on 29th September 2017. We can/should remove the support for this version since it's only causing compatibility issues with other packages and case DeprecationWarnings (see this PR as an example of both: https://github.com/gotcha/ipdb/pull/162 )

Remove Python 3.3.x support

---

AUTHORS
HISTORY.txt
ipdb/__main__.py
setup.py

Fixes #144.
The deprecation warning is particularly annoying in my development setup where warnings are treated as failures during tests.
Since IPython 5.1.0, `shell.colors` is the value used for `color_scheme` anyway. See https://github.com/ipython/ipython/blob/5.1.0/IPython/core/debugger.py#L240.
`ipdb` still supports IPython 5.0 so it may make sense to either bump that dependency to 5.1 or add additional code to keep compatibility with IPython 5.0. I'm not sure which approach you prefer.

Stop setting deprecated color_scheme argument.

---

ipdb/__main__.py

As per https://docs.python.org/3/library/getopt.html?highlight=getopt#getopt.getopt , the leading `--` must not be included. Currently, suppying e.g. `--help` produces `GetoptError: option --help not recognized`

Fix long options

---

ipdb/__main__.py

Fixes #128 
```
$ cat problem.py
from IPython.terminal.ipapp import TerminalIPythonApp
ipapp = TerminalIPythonApp()
ipapp.interact = False
ipapp.initialize([])
shell = ipapp.shell
$ python problem.py > flah
$ od -xa flah
0000000      5d1b    3b30    5049    7479    6f68    3a6e    7320    7365
esc   ]   0   ;   I   P   y   t   h   o   n   :  sp   s   e   s
0000020      772f    0007
/   w bel
0000023
```
And with the fix:
``` 
$ cat test.py
from IPython.terminal.ipapp import TerminalIPythonApp
ipapp = TerminalIPythonApp()
ipapp.interact = False
ipapp.initialize(['--no-term-title'])
shell = ipapp.shell
$ python test.py >flah
$ od -xa flah
```
(no output from the second octal dump)

Avoid emitting term-title bytes

---

setup.py

Appears to not be necessary anymore (at least no changes for py37 for
me), and prevents editable installs.
Initially done for https://github.com/gotcha/ipdb/pull/16.
This reverts commit d86c166b61aa711e6b0197c3d914031c0651ca15.

Revert "Add use_2to3 keyword to setup()."

---

README.rst

Fix simple typo: explicitely -> explicitly

---

HISTORY.txt
README.rst
ipdb/__main__.py
tests/test_config.py

Add option to retrieve context from environment variable `IPDB_CONTEXT_SIZE` or from `setup.cfg` file.

Add option to use context from env var or config file

---

HISTORY.txt
README.rst
ipdb/__main__.py

Add condition variable to set_trace to show console only when ``cond=True``.
This way, instead of doing
```
for abc in range(1, 100):
if abc == 13:
import ipdb; ipdb.set_trace()
```
You do this
```
for abc in range(1, 100):
import ipdb; ipdb.set_trace(cond=(abc==13))
```

Add condition variable to set_trace

---

HISTORY.txt
ipdb/__main__.py
setup.py
tests/test_opts.py

This adds a `-m` option that was introduced in Python 3.7 pdb. It is
implemented in a backward-compatible way: if the version of python is
lower than 3.7, the script will fallback to shortopts without -m.
See #192.
- Added `-m` option
- Added `test/test_opts.py` for coverage
- Added `mock` to `tests_require` in `setup.py`, so that tests work with Python 2.7.

Add -m option

---

AUTHORS
HISTORY.txt
setup.py

See [here](https://github.com/ipython/ipython/blob/master/setup.py#L44):
```
IPython 7.17+ supports Python 3.7 and above, following NEP 29.
When using Python 2.7, please install IPython 5.x LTS Long Term Support version.
Python 3.3 and 3.4 were supported up to IPython 6.x.
Python 3.5 was supported with IPython 7.0 to 7.9.
Python 3.6 was supported with IPython up to 7.16.
```

Fix ipython version for python 3.6

---

ipdb/__main__.py
setup.py
tests/test_config.py

Related: https://github.com/gotcha/ipdb/issues/218

Change toml file read to actually use toml instead of configparser

---

setup.py

The code will always use 'unittest.mock' in Python 3, so stop pulling
the 'mock' package unnecessarily.

setup.py: Do not require mock in Python 3

---

HISTORY.txt
README.rst
ipdb/__init__.py
ipdb/__main__.py
setup.py
tests/test_import.py

Fixes #215.
I chose `iex` (**i**pdb **ex**ception) instead of my previous conflicting `pm`. It's a concise name because that's how I like my debugging tools (and I assume the existing `pm` was also chosen for conciseness). If that's not acceptable here, I think I'll instead try to figure out a good way to make `launch_ipdb_on_exception` itself a function decorator, so it can be imported as `from ipdb import launch_ipdb_on_exception as iex`.

Support launch_ipdb_on_exception as a function decorator

---

ipdb/__main__.py

Carefully tests if `pyproject.toml` contains a `tool` section

---

.travis.yml

Reverts #208. This was a marketing campaign via PR by IBM. This project is pure python so does not need testing on alternative CPU architectures. And no one reported any problems with ppc64le, because basically no one uses it.

Remove ppc64le tests

---

HISTORY.txt
ipdb/__main__.py
tests/test_opts.py

The fix for python 3.11+ to use `_run` instead was not working for me, but the tests were also still checking for the old code path as well.  Comments welcome, not sure if you want this in a different style or format or whatever.
I tested a local install and it fixed my issues I was having.  Before this fix, I was getting the following error on 3.11
```
Traceback (most recent call last):
File "C:\Users\Andrew\AppData\Local\Programs\Python\Python311\Lib\site-packages\ipdb\__main__.py", line 322, in main
pdb._runscript(mainpyfile)
^^^^^^^^^^^^^^
AttributeError: 'TerminalPdb' object has no attribute '_runscript'
```

fix python 3.11+ and update tests

---

HISTORY.txt
ipdb/__main__.py

Use context manager for file opening, will close file properly once work is finished.
I found this poking around and running the unit tests and seeing lots of these warnings:
```
/opt/hostedtoolcache/Python/3.11.0/x64/lib/python3.11/tomllib/_parser.py:66: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/tmp0agdoy89/cwd/pyproject.toml'>
return loads(s, parse_float=parse_float)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

Use context manager for toml file open.

---

README.rst

Replace broken Travis CI badge with a GitHub Actions one.

Fix CI badge
